name: Call Other Flows
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  lets_call:

    strategy:
      matrix:
        target: [dev, qa]

    uses: ./.github/workflows/matrix-run.yml
